### ISSUE TITLE
When running the ansible playbook, have the ability to do a docker login

### ISSUE THREAD

**Issue by julienchastang** [zonca/jupyterhub-deploy-kubernetes-jetstream#66]
[With DockerHub download limits in place](https://www.docker.com/increase-rate-limits/), it has become important to provide a mechanism to authenticate with DockerHub. One probably needs to do something like this in the playbook:

```yaml
---
- name: Simple Docker Login
  hosts: {{ myhosts_or_somesuch }}
  tasks:
    - name: Log into DockerHub
      community.docker.docker_login:
        username: "{{ docker_username }}"
        password: "{{ docker_password }}"
      no_log: true  # To prevent sensitive data from being logged
```

However, I am not sure what I should set for the `hosts` tag or if there is a better way to do this.
