### ISSUE TITLE
Test reliability of persistent volumes

### ISSUE THREAD

**Issue by zonca** [zonca/jupyterhub-deploy-kubernetes-jetstream#8]
Relatedly, is it also possible to update kubernetes itself, safely without loosing user data via the ansible playbook? Basically, I want a seamless user experience as the jupyterhub migrates forward.

I would like to test this, user data are in persistent volumes so in principle even if we year everything down and redeploy, if JupyterHub is referencing persistent volumes by name, a user should get their data back.

_Originally posted by @julienchastang in https://github.com/zonca/jupyterhub-deploy-kubernetes-jetstream/issues/7#issuecomment-466696356_

**Comment by julienchastang** [comment]
When you mean tear everything down, do you mean [this](https://zero-to-jupyterhub.readthedocs.io/en/stable/turn-off.html)?  Will those tear down procedures also take down the persistent volumes?

Relatedly, it would be nice if the openstack volume had names that could be identified to a user and also the cluster it is attached to. Currently, it looks like this:

```
+--------------------------------------+-------------------------------------------------------------+-----------+------+---------------------------------------------------------------+
| ID                                   | Name                                                        | Status    | Size | Attached to                                                   |
+--------------------------------------+-------------------------------------------------------------+-----------+------+---------------------------------------------------------------+
| 3cca8077-99a9-4f7a-93a4-3a2926b1349c | kubernetes-dynamic-pvc-a4487305-2415-11e9-b7c5-fa163ee120af | available |    1 |                                                               |
| 85b74fb3-70f3-44fb-8eea-da5417b7c2fd | kubernetes-dynamic-pvc-79633487-1e92-11e9-95b7-fa163e9a87b9 | in-use    |    1 | Attached to unidata-jupyterhub-k8s-node-nf-2 on /dev/sdb      |
+--------------------------------------+-------------------------------------------------------------+-----------+------+---------------------------------------------------------------+
```

with no meaningful information about the provenance of the volume especially when not "in-use".

**Comment by julienchastang** [comment]
Just confirming/clarifying that by tearing everything down, we mean running:

```
helm delete jhub --purge
kubectl delete namespace jhub
```

followed by

`terraform_destroy.sh`. 

In theory, the persistent volumes should remain intact after issuing the commands above. Correct?

Also, is that last `terraform` command overkill? Ideally I would like to preserve the IP of the master node to avoid DNS name headaches. Is that achievable?

**Comment by zonca** [comment]
I am testing this, probably tomorrow

**Comment by zonca** [comment]
ok, I added a section at: https://zonca.github.io/2018/09/kubernetes-jetstream-kubespray-jupyterhub.html

**Comment by zonca** [comment]
about naming the openstack volumes with the user name, I have searched for a way to do that, but there are so many layers I've no idea where that is coming from.
Currently can backup the pairing between Openstack volume and users with:

    kubectl get pv -n jhub -o yaml > pv.yaml

there, you have reference to the Openstack volume and the user name:

```
  cinder:                                                                                                                           
    volumeID: f05b30e6-e1c9-48dc-b3bf-8ccf91123e2d                                                                                  
  claimRef:                                                                                                                         
    apiVersion: v1                                                                                                                  
    kind: PersistentVolumeClaim                                                                                                     
    name: claim-zonca 
```
